Repository sequentech/documentation, pull requests merged in 2023-06, with the labels that each got.

#117 Alternative Auth methods support
  docs/general/reference/election-creation-json.md
Labels: enhancement

#120 🐞Fix documentation link to deployment config
  docs/general/guides/deployment/assets/config.auth.yml
  docs/general/guides/deployment/assets/config.master.yml
  docs/general/guides/deployment/deployment.md
Labels: bug, documentation

#121 🐞Fix documentation link to deployment config (#120)
  docs/general/guides/deployment/assets/config.auth.yml
  docs/general/guides/deployment/assets/config.master.yml
  docs/general/guides/deployment/deployment.md
Labels: bug, documentation

#119 ✨dynamic position of invalid vote option
  docs/general/guides/write-ins/write-ins.md
  docs/general/reference/election-creation-json.md
Labels: documentation, enhancement

#122 ✨dynamic position of invalid vote option (#119)
  docs/general/guides/write-ins/write-ins.md
  docs/general/reference/election-creation-json.md
Labels: documentation, enhancement

#118 ✨ Countdown until logout
  docs/general/concepts/browsers-and-cookies/assets/logout-progress.png
  docs/general/concepts/browsers-and-cookies/assets/logout-tooltip.png
  docs/general/concepts/browsers-and-cookies/browsers-and-cookies.md
  docs/general/reference/election-creation-json.md
Labels: enhancement, breaking-change
