Repository sequentech/documentation, pull requests merged in 2023-09, with the labels that each got.

#131 alternative auth methods: switch back to smartlink tab fails
  docs/general/guides/messaging-voters/messaging-voters.md
  docs/general/reference/election-creation-json.md
Labels: documentation

#136 Add italian i18n
  docs/general/contribute/translation/assets/poeditor_export.png
  docs/general/contribute/translation/translation.md
Labels: enhancement

#133 ✨ Role-based login for election manager
  docs/general/reference/reference.md
  docs/general/reference/user-permissions.md
Labels: documentation, enhancement, breaking-change

#132 ✨ Support search/filter candidates feature in voting booth
  docs/general/reference/election-creation-json.md
Labels: documentation, enhancement

#135 ✨ Voting-booth: Improve election info in the ballot ticket PDF for parent-children elections
  docs/general/reference/election-creation-json.md
Labels: documentation, enhancement

#134 Automated start/stop support
  docs/general/guides/guides.md
  docs/general/guides/scheduled-events/assets/activity-log.png
  docs/general/guides/scheduled-events/assets/dialog-selector.png
  docs/general/guides/scheduled-events/assets/dialog.png
  docs/general/guides/scheduled-events/assets/election-dashboard.png
  docs/general/guides/scheduled-events/assets/notification.png
  docs/general/guides/scheduled-events/scheduled-events.md
  docs/general/reference/election-creation-json.md
Labels: documentation
